server:
  port: 8080

spring:
  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/./snack-ex;MODE=MySQL;
    username: SA

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379
